name: 'Build and Push'
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 코드 취약점 분석
      - name: Run Trivy vulnerability scanner for code
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-code-results.sarif'
          severity: 'HIGH,CRITICAL,MEDIUM'
          timeout: '10m'

      - name: Upload Trivy code scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-code-results.sarif'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: layer6ai/lab-github-actions-trivy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write
    steps:
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'layer6ai/lab-github-actions-trivy:latest'
          format: 'sarif'
          exit-code: 1 # 취약점이 발견되면 작업 실패
          severity: 'HIGH,CRITICAL,MEDIUM'
          output: 'trivy-image-results.sarif'

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'
